Class {
	#name : #Combi,
	#superclass : #Object,
	#instVars : [
		'patente',
		'tipo',
		'chofer',
		'cantidadAsientos'
	],
	#category : #'IngSoftII-model'
}

{ #category : #accessing }
Combi >> cantidadAsientos [
	^ cantidadAsientos
]

{ #category : #accessing }
Combi >> chofer [
	^ chofer
]

{ #category : #accessing }
Combi >> patente [
	^ patente
]

{ #category : #accessing }
Combi >> tipo [
	^ tipo
]
