Class {
	#name : #Ruta,
	#superclass : #Object,
	#instVars : [
		'lugarOrigen',
		'lugarDestino',
		'combi',
		'horario',
		'distancia'
	],
	#category : #'IngSoftII-model'
}

{ #category : #accessing }
Ruta >> combi [
	^ combi
]

{ #category : #accessing }
Ruta >> distancia [
	^ distancia
]

{ #category : #accessing }
Ruta >> horario [
	^ horario
]

{ #category : #accessing }
Ruta >> lugarDestino [
	^ lugarDestino
]

{ #category : #accessing }
Ruta >> lugarOrigen [
	^ lugarOrigen
]
